### ISSUE TITLE
Support for deleted files

### ISSUE THREAD

**Issue by brandoncamenisch** [grvcoelho/lint-diff#3]
I was working this into a CI setup and noticed that it fails if a file or directory was deleted in the commit.

`fatal: ambiguous argument 'filename': unknown revision or path not in the working tree.`

**Comment by grvcoelho** [comment]
Hi @brandoncamenisch thanks for reporting this issue.

I just published `v0.5.3` to fix this and it should be working just fine now :tada:

**Comment by brandoncamenisch** [comment]
Wow, awesome that was fast. And it works :smile:
