### ISSUE TITLE
Returns exit code 1 when there are errors in changed file but not in changed lines

### ISSUE THREAD

**Issue by bsuh** [grvcoelho/lint-diff#7]
If the file you are changing already has linter errors but you add lines with no linter errors, lint-diff returns exit code 1.

**Comment by grvcoelho** [comment]
Hey @bsuh, can you provide a working example with this scenario?

**Comment by bsuh** [comment]
https://github.com/bsuh/lint-diff-example

It has two commits. First introduces index.js with ESLint error. Second commit adds comment on different line, not introducing any ESLint errors.
```
npm install
npx lint-diff HEAD~1
echo $?
```

Exit code is 1 although lint-diff output is empty.

Here is my fix https://github.com/bsuh/lint-diff/commit/ea63d921725d25166005be40405b845afef1ea8e

**Comment by peteychuk** [comment]
Hi guys,

Any luck on this?

**Comment by grvcoelho** [comment]
@peteychuk @bsuh, @flyingluscas: just published the fix to `1.2.1`. Thanks a lot @flyingluscas for the PR :tada:

**Comment by peteychuk** [comment]
Thanks guys! I appreciate quick publishing.
